version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=adj0AGZ7cgu9vbe@ryt
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysqldb:/var/lib/mysql
